[project]
name = "physical-ai-hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "lerobot[dynamixel]>=0.4.3",
    "mimic-video>=0.0.47",
    "numpy>=2.4.2",
    "pytest>=9.0.2",
]
